language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-feed-api
  - docker build -t udagram-feed-api-image .
  - docker tag udagram-feed-api-image shahjuhi1108/udagram-feed-api-image:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shahjuhi1108/udagram-feed-api-image
